name: habito_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  gap: ^3.0.1
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  very_good_analysis: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
